'use strict';
/* ═══════════════════════════════════════════════════════════════════════════
   scripts/seed-demo.js — build a showcase workspace, through the real API
   ───────────────────────────────────────────────────────────────────────────
   Creates one account and fills it with content that is coherent across every
   module, so the product demonstrates its own thinking rather than just
   showing populated tables.

     node scripts/seed-demo.js --url https://… --email … --password …

   ── EVERY ROW GOES THROUGH THE REAL ENDPOINTS ─────────────────────────────
   Nothing here talks to PostgreSQL. It registers over /auth/register, holds a
   real session cookie, and POSTs to the same routes the browser uses — so
   every validator, every owner-scoping rule and every guard runs exactly as
   it does for a customer. A seeder that writes straight to the database can
   create rows the application would have refused, and then the demo is
   showing a state the product cannot actually reach.

   On this platform that is not merely a principle, it is the only option:
   DATABASE_URL points at `postgres.railway.internal`, which resolves only
   inside Railway. There is no direct-write shortcut to be tempted by.

   ── THE CONTENT IS REAL, NOT LOREM ────────────────────────────────────────
   Every document is generated by the live model through POST /api/generate,
   which means every word_count, seo_score and readability figure on the
   dashboard was computed from text the product actually produced. Seeding
   pre-written strings through POST /api/documents would leave seo_score at 0
   on every row — a quality dashboard reading zero everywhere demonstrates
   nothing except that the column exists.

   It also means the trilingual work is demonstrated rather than asserted:
   the Chinese documents carry real four-hundred-word counts, which is the
   whole point of UPGRADE-SPEC §0.7. Before this round they would every one
   have read `1`.

   ── BUILT BACKWARDS FROM WHAT M-Ai NOTICES ────────────────────────────────
   M-Ai has 18 tools and they are only interesting if the data gives them
   something to say. So the fixture is designed against them:

     · documents spread over 7 tool_ids     -> documents_by_tool
     · deliberate long/short mix            -> document_quality_scores spread,
                                               and low_scoring_documents fires
     · three languages                      -> the trilingual story, and the
                                               CJK counter visibly working
     · two PR releases, one draft one not   -> pr_release_pipeline
     · brand profile filled                 -> brand_profile

   ── IT IS OBVIOUSLY A DEMO ────────────────────────────────────────────────
   One fictional Malaysian SME. Suria Teknologi Sdn Bhd does not exist, the
   email domain is a reserved `.example.com`, and nothing here should ever be
   mistaken for a real customer's records.
   ═══════════════════════════════════════════════════════════════════════════ */

const https = require('https');
const http = require('http');

/* ── args ────────────────────────────────────────────────────────────────── */
const args = {};
process.argv.slice(2).forEach((a, i, arr) => {
  if (a.startsWith('--')) args[a.slice(2)] = arr[i + 1] && !arr[i + 1].startsWith('--') ? arr[i + 1] : true;
});
const BASE = String(args.url || 'http://127.0.0.1:3000').replace(/\/$/, '');
const EMAIL = String(args.email || '');
const PASSWORD = String(args.password || '');
const NAME = String(args.name || 'Aisyah Rahman');
const COMPANY = 'Suria Teknologi Sdn Bhd';
const SKIP_IMAGES = !!args['skip-images'];
/* Resume point into DOCS. A dropped socket does NOT prove the generation
   failed — the model may have finished and the row been written while only
   the response was lost — so a blind re-run can duplicate documents. Check
   what actually landed, then resume past it. */
const FROM = Number(args.from || 0);
const SKIP_PR = !!args['skip-pr'];

let cookie = '';
const made = { documents: 0, pr: 0, images: 0 };
const failures = [];

/* ── transport ───────────────────────────────────────────────────────────── */
function req(method, path, body) {
  return new Promise((resolve, reject) => {
    const u = new URL(path, BASE);
    const lib = u.protocol === 'https:' ? https : http;
    const payload = body === undefined ? null : Buffer.from(JSON.stringify(body));
    const r = lib.request({
      hostname: u.hostname,
      port: u.port || (u.protocol === 'https:' ? 443 : 80),
      path: u.pathname + u.search,
      method,
      headers: {
        ...(cookie ? { Cookie: cookie } : {}),
        ...(payload ? { 'Content-Type': 'application/json', 'Content-Length': payload.length } : {}),
        Accept: 'application/json',
      },
      timeout: 240000,
    }, (res) => {
      const sc = res.headers['set-cookie'];
      if (sc) cookie = sc.map((c) => c.split(';')[0]).join('; ');
      /* COLLECT BUFFERS, DECODE ONCE.
         `data += chunk` decodes each chunk as UTF-8 independently, so a
         multi-byte character that straddles a chunk boundary is destroyed —
         the two halves each decode to U+FFFD. On an EN-only payload you would
         never notice. This script generates Chinese, where every character is
         three bytes, and it showed up immediately: a product description read
         back as `拥有大面积���顶` instead of `屋顶`.

         The database was fine — verified by fetching the same row with curl
         and counting zero U+FFFD. The corruption existed only in what this
         script printed, which is the more dangerous kind: it would have been
         read as evidence that the platform mangles Chinese. */
      const chunks = [];
      res.on('data', (d) => { chunks.push(d); });
      res.on('end', () => {
        const data = Buffer.concat(chunks).toString('utf8');
        let json = null;
        try { json = JSON.parse(data); } catch { /* html or empty; status is the signal */ }
        resolve({ status: res.statusCode, body: json, raw: data.slice(0, 300) });
      });
    });
    r.on('timeout', () => r.destroy(new Error('timeout')));
    /* A TRANSPORT ERROR IS A RESULT, NOT AN EXCEPTION.
       The first run of this script died on `read ECONNRESET` five documents
       in: the retry loop below only understood HTTP status codes, so a socket
       the proxy dropped mid-generation rejected the promise and took the whole
       seed with it — leaving a half-populated workspace, which is the exact
       failure mode this script exists to avoid.
       Long generations are precisely when the connection is most likely to be
       cut, so this is the common case, not the edge one. Resolve with status 0
       and let the caller's retry policy decide. */
    r.on('error', (err) => resolve({ status: 0, body: null, raw: String(err.message || err) }));
    if (payload) r.write(payload);
    r.end();
  });
}

const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

/* Groq's preview tier rate-limits hard, and a 429 mid-seed would leave a
   half-populated workspace that looks like a product defect rather than a
   throttle. Retry with a widening gap, and give up loudly rather than
   silently skipping a document. */
async function generate(payload, label) {
  for (let attempt = 1; attempt <= 5; attempt++) {
    const r = await req('POST', '/api/generate', payload);
    if (r.status === 200 && r.body && r.body.success) return r.body;
    // status 0 is a dropped socket — see req()'s error handler. It is the most
    // retryable thing here, not the least.
    const retryable = r.status === 0 || r.status === 429 || r.status >= 500;
    if (!retryable || attempt === 5) {
      failures.push(`${label}: HTTP ${r.status} ${(r.body && r.body.error) || r.raw}`);
      return null;
    }
    const wait = attempt * 20000;
    console.log(`      throttled (${r.status}) — waiting ${wait / 1000}s then retrying`);
    await sleep(wait);
  }
  return null;
}

/* ── the fixture ─────────────────────────────────────────────────────────── */

/* Suria Teknologi: rooftop solar and IoT energy monitoring for Malaysian SMEs.
   Every prompt below is a real brief a marketer at that company would write.
   `long` drives the length, which is what actually moves seo_score — the mix
   is deliberate so the quality dashboard has a spread and M-Ai's
   low_scoring_documents tool has something true to report. */
const DOCS = [
  // ── English ──────────────────────────────────────────────────────────────
  { lang: 'en', toolId: 'blog-post', toolName: 'Blog Post', long: true,
    prompt: 'Write a comprehensive, SEO-optimised blog post titled "How Malaysian SMEs Cut Electricity Costs 40% With Rooftop Solar". Target keywords: rooftop solar Malaysia, SME energy costs, NEM 3.0. Audience: factory and warehouse owners in Selangor and Johor. Use ## H2 and ### H3 headings, include a worked RM cost example, practical steps, and a conclusion with a call to action.' },
  { lang: 'en', toolId: 'landing-page', toolName: 'Landing Page Copy', long: true,
    prompt: 'Write complete landing page copy for Suria Teknologi\'s solar + energy monitoring package for Malaysian SMEs. Value proposition: see every ringgit of energy spend in real time, and cut it. Include HERO HEADLINE, HERO SUB-HEADLINE, 3 BENEFIT SECTIONS, SOCIAL PROOF, HOW IT WORKS in 3 steps, FAQ with 3 questions, and a FINAL CTA.' },
  { lang: 'en', toolId: 'email-campaign', toolName: 'Email Campaign', long: false,
    prompt: 'Write a short follow-up email to a factory owner in Shah Alam who requested a rooftop solar quotation two weeks ago and has not replied. Warm, not pushy. One clear call to action to book a site survey.' },
  { lang: 'en', toolId: 'ad-copy', toolName: 'Ad Copy', long: false,
    prompt: 'Write 3 short Facebook ad variants for a free rooftop solar savings assessment for Malaysian SME factory owners. Each under 40 words.' },
  { lang: 'en', toolId: 'seo-article', toolName: 'SEO Article', long: true,
    prompt: 'Write an in-depth SEO article explaining Malaysia\'s Net Energy Metering (NEM) scheme for small and medium businesses: what it is, who qualifies, how the credits work, and what a typical payback period looks like. Target keyword: NEM Malaysia SME. Use headings and a summary table in markdown.' },

  // ── Bahasa Malaysia ──────────────────────────────────────────────────────
  { lang: 'ms', toolId: 'blog-post', toolName: 'Blog Post', long: true,
    prompt: 'Write a comprehensive blog post about how Malaysian SMEs can reduce electricity bills with rooftop solar, covering the NEM scheme, a worked RM cost example, and the steps to get started. Audience: factory owners. Use headings and end with a call to action.' },
  { lang: 'ms', toolId: 'social-post', toolName: 'Social Media Post', long: false,
    prompt: 'Write 3 short Facebook posts announcing a free rooftop solar savings assessment for SME factory owners. Friendly, with a clear call to action.' },
  { lang: 'ms', toolId: 'email-campaign', toolName: 'Email Campaign', long: false,
    prompt: 'Write a short follow-up email to a factory owner who asked for a solar quotation two weeks ago and has not replied. Warm and helpful, one call to action to book a site survey.' },

  // ── Chinese — the CJK counter is the point ───────────────────────────────
  { lang: 'zh', toolId: 'blog-post', toolName: 'Blog Post', long: true,
    prompt: 'Write a comprehensive blog post explaining how Malaysian SMEs can cut electricity costs with rooftop solar: how the NEM scheme works, a worked RM cost example, the payback period, and how to begin. Audience: factory and warehouse owners. Use headings and finish with a call to action.' },
  { lang: 'zh', toolId: 'product-description', toolName: 'Product Description', long: false,
    prompt: 'Write a product description for a rooftop solar and IoT energy-monitoring package sold to Malaysian SMEs. Cover what is included, the main benefit, and who it suits.' },
  { lang: 'zh', toolId: 'social-post', toolName: 'Social Media Post', long: false,
    prompt: 'Write 3 short social posts announcing a free rooftop solar savings assessment for SME factory owners in Malaysia. Include a clear call to action.' },

  // ── Deliberately thin, so the quality tools have something true to say ───
  { lang: 'en', toolId: 'social-post', toolName: 'Social Media Post', long: false,
    prompt: 'Write one very short tweet, under 20 words, announcing that Suria Teknologi now installs battery storage.' },
];

const PR = [
  { company: COMPANY, lang: 'en',
    headline: 'Suria Teknologi Launches Battery Storage for Malaysian SMEs',
    keyMessages: 'Suria Teknologi has added lithium battery storage to its rooftop solar package for Malaysian small and medium businesses. Early installations at three Selangor factories cut evening grid draw by an average of 38%. The package is available from RM48,000 with a seven-year warranty and integrates with the company\'s existing IoT energy monitoring dashboard.',
    quote: 'Solar solved the daytime bill. Storage is what finally solved the evening one.',
    spokesperson: 'Aisyah Rahman, Managing Director', audience: 'Trade and business media', region: 'Malaysia',
    cta: 'Book a free site survey at suriateknologi.example.com', tone: 'Professional' },
  { company: COMPANY, lang: 'en',
    headline: 'Suria Teknologi Passes 100 Rooftop Installations Across Selangor and Johor',
    keyMessages: 'Suria Teknologi Sdn Bhd has completed its one hundredth commercial rooftop solar installation, spanning 62 sites in Selangor and 38 in Johor. Combined installed capacity is 4.2 MWp. The company reports an average payback period of 4.1 years for its SME customers under the NEM scheme.',
    quote: 'A hundred roofs is not a vanity number. It is a hundred businesses paying less every month.',
    spokesperson: 'Aisyah Rahman, Managing Director', audience: 'Business and energy media', region: 'Malaysia',
    cta: 'Read the full installation report at suriateknologi.example.com', tone: 'Professional' },
];

const IMAGES = [
  { prompt: 'Wide photograph of a modern Malaysian factory rooftop covered in neatly aligned solar panels under bright tropical morning light, palm trees and low industrial buildings in the background, clean documentary style, no text, no logos',
    size: '1664*928' },
  { prompt: 'Clean product photograph of a wall-mounted white energy monitoring display unit showing a simple dashboard, mounted on a light grey office wall, soft even studio lighting, minimal composition, no text, no logos',
    size: '1328*1328' },
  { prompt: 'Two engineers in high-visibility vests and hard hats inspecting solar panels on a commercial rooftop in Malaysia, warm late afternoon light, candid documentary photography, no text, no logos',
    size: '1472*1104' },
];

/* ── run ─────────────────────────────────────────────────────────────────── */
async function main() {
  if (!EMAIL || !PASSWORD) {
    console.error('--email and --password are required');
    process.exit(1);
  }
  console.log('\nSeeding demo workspace');
  console.log('  target : ' + BASE);
  console.log('  account: ' + EMAIL + '\n');

  /* 1. account — register, or sign in if it already exists (idempotent) */
  console.log('1. account');
  let r = await req('POST', '/auth/register', { name: NAME, email: EMAIL, password: PASSWORD });
  if (r.status === 200 || r.status === 201) {
    console.log('   ✓ registered');
  } else {
    console.log('   · register said ' + r.status + ' (' + ((r.body && r.body.error) || '').slice(0, 60) + ') — signing in instead');
    r = await req('POST', '/auth/login', { email: EMAIL, password: PASSWORD });
    if (r.status !== 200) {
      console.error('   ✗ could not register OR sign in: ' + r.status + ' ' + r.raw);
      process.exit(1);
    }
    console.log('   ✓ signed in to the existing account');
  }

  const me = await req('GET', '/auth/me');
  if (me.status !== 200) { console.error('   ✗ no session after auth: ' + me.status); process.exit(1); }
  console.log('   ✓ session held');

  /* 2. brand profile — this is what steers every generation below */
  console.log('\n2. brand profile');
  r = await req('PUT', '/api/auth/me', {
    name: NAME,
    brand_name: COMPANY,
    brand_desc: 'Suria Teknologi Sdn Bhd installs rooftop solar and IoT energy monitoring for Malaysian small and medium businesses — factories, warehouses and cold-storage operators in Selangor and Johor. We sell measurable savings on the electricity bill, not panels. Customers are practical owner-operators who care about payback period, NEM credits and whether the system keeps working in year eight.',
    brand_tone: 'Professional',
  });
  console.log(r.status === 200 ? '   ✓ brand set — every generation below inherits it' : '   ✗ brand ' + r.status);

  /* 3. content — real generations, real scores */
  console.log('\n3. content (live model — this is the slow part)');
  if (FROM > 0) console.log(`   resuming at index ${FROM}; ${FROM} earlier document(s) already exist`);
  for (let di = FROM; di < DOCS.length; di++) {
    const d = DOCS[di];
    const label = `${di}. ${d.lang}/${d.toolId}`;
    process.stdout.write(`   ${label.padEnd(26)}`);
    const out = await generate({
      prompt: d.prompt,
      toolId: d.toolId,
      toolName: d.toolName,
      tone: 'Professional',
      variants: 1,
      lang: d.lang,
    }, label);
    if (out) {
      made.documents++;
      const verified = out.langVerified === false ? ' ⚠ langVerified=false' : '';
      console.log(`✓ ${String(out.wordCount).padStart(4)} words · seo ${String(out.seoScore).padStart(3)} · read ${String(out.readability).padStart(3)}${verified}`);
    } else {
      console.log('✗');
    }
    await sleep(4000); // pace against the preview-tier rate limit
  }

  /* 4. PR releases */
  console.log('\n4. press releases');
  for (const p of PR) {
    process.stdout.write(`   ${p.headline.slice(0, 46).padEnd(48)}`);
    /* SAME RETRY AS THE DOCUMENTS, and it was missing here on the first run.
       Both press releases failed with 500, and the production log showed why:
         Rate limit reached ... TPM: Limit 8000, Used 6947, Requested 3359
       Groq's free tier allows 8,000 tokens per minute and a press release
       asks for ~3,300 on top of whatever the previous document just spent.
       The documents survived it because they retried; these did not, because
       I wrote a bare request here. Not a product defect — a gap in the seeder. */
    let rr = null;
    for (let attempt = 1; attempt <= 6; attempt++) {
      rr = await req('POST', '/api/pr/generate', p);
      if (rr.status === 200 && rr.body && rr.body.success !== false) break;
      const retryable = rr.status === 0 || rr.status === 429 || rr.status >= 500;
      if (!retryable || attempt === 6) break;
      const wait = 25000 + attempt * 10000;
      console.log(`\n      throttled (${rr.status}) — waiting ${wait / 1000}s then retrying`);
      await sleep(wait);
      process.stdout.write(`   ${'retry'.padEnd(48)}`);
    }
    if (rr && rr.status === 200 && rr.body && rr.body.success !== false) {
      made.pr++;
      const g = rr.body.geoScore !== undefined ? ` · geo ${rr.body.geoScore}` : '';
      console.log(`✓ ${String(rr.body.wordCount || '?').padStart(4)} words${g}`);
    } else {
      failures.push(`PR "${p.headline.slice(0, 30)}": ${rr.status} ${(rr.body && rr.body.error) || rr.raw}`);
      console.log('✗ ' + rr.status);
    }
    await sleep(6000);
  }

  /* 5. images — real Qwen generations, re-hosted by the platform */
  if (SKIP_IMAGES) {
    console.log('\n5. images — skipped (--skip-images)');
  } else {
    console.log('\n5. images (live Qwen-Image, downloaded and re-hosted)');
    for (const im of IMAGES) {
      process.stdout.write(`   ${im.size.padEnd(12)}${im.prompt.slice(0, 40).padEnd(42)}`);
      const ir = await req('POST', '/api/images/generate', im);
      if (ir.status === 201 && ir.body && ir.body.image) {
        made.images++;
        const img = ir.body.image;
        console.log(`✓ ${img.status} · ${img.byte_size ? Math.round(img.byte_size / 1024) + 'KB' : '?'}`);
      } else {
        failures.push(`image ${im.size}: ${ir.status} ${(ir.body && (ir.body.message || ir.body.error)) || ir.raw}`);
        console.log('✗ ' + ir.status + ' ' + String((ir.body && (ir.body.reason || ir.body.error)) || '').slice(0, 40));
      }
      await sleep(3000);
    }
  }

  /* 6. what the workspace actually holds now */
  console.log('\n6. verification — reading it back through the API');
  const stats = await req('GET', '/api/stats');
  if (stats.status === 200) console.log('   /api/stats  ' + JSON.stringify(stats.body));
  const docs = await req('GET', '/api/documents/');
  const sub = await req('GET', '/api/subscription/status');
  if (sub.status === 200) console.log('   subscription ' + JSON.stringify(sub.body).slice(0, 160));

  console.log('\n─────────────────────────────────────────────');
  console.log(`  documents generated : ${made.documents}/${DOCS.length}`);
  console.log(`  press releases      : ${made.pr}/${PR.length}`);
  console.log(`  images              : ${made.images}/${SKIP_IMAGES ? 0 : IMAGES.length}`);
  if (failures.length) {
    console.log(`\n  ${failures.length} failure(s) — NOT hidden:`);
    failures.forEach((f) => console.log('    · ' + f));
  } else {
    console.log('\n  no failures');
  }
  console.log('');
}

main().catch((e) => { console.error('\nFATAL: ' + e.message); process.exit(1); });
